[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"  
via_ir = false

# Suppress linter warnings
[profile.default.lint]
ignore = ["mixed-case-function"]



# Fuzz testing configuration
[profile.default.fuzz]
runs = 256

# Invariant testing configuration
[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false

# Gas reporting
[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

# RPC endpoints
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/YOUR_INFURA_KEY"
mainnet = "https://mainnet.infura.io/v3/YOUR_INFURA_KEY"
# Add more networks as needed
goerli = "https://goerli.infura.io/v3/YOUR_INFURA_KEY"
polygon = "https://polygon-rpc.com"
arbitrum = "https://arb1.arbitrum.io/rpc"

# Etherscan API keys for verification
[etherscan]
sepolia = { key = "YOUR_ETHERSCAN_API_KEY" }
mainnet = { key = "YOUR_ETHERSCAN_API_KEY" }
goerli = { key = "YOUR_ETHERSCAN_API_KEY" }
polygon = { key = "YOUR_POLYGONSCAN_API_KEY", url = "https://api.polygonscan.com/api" }
arbitrum = { key = "YOUR_ARBISCAN_API_KEY", url = "https://api.arbiscan.io/api" }